name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      
      - name: Install dependencies
        working-directory: backend/Storix
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        
      - name: Configure DATABASE_URL
        run: echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

      
      - name: Run migrations
        working-directory: backend/Storix
        run: python manage.py migrate --noinput

      
      - name: Run tests with coverage
        working-directory: backend/Storix
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml
          coverage report

      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
